[package]
name = "ipc"
version = "0.0.4"
edition = "2024"

[features]
default = []
x11 = ["tmui/x11"]

[dependencies]
tmui = { git = "https://github.com/toocol/tmui" }
termio = { workspace = true }
godot = { workspace = true }

log = { workspace = true }
